---
- name: WordPress Server
  hosts: web
  sudo: yes
  remote_user: ubuntu
  roles:
    - { role: common, tags: [common] }
    - { role: ferm, tags: [ferm] }
    - { role: users, tags: [users] }
    - { role: sshd, tags: [sshd] }
    - { role: php, tags: [php] }
    - { role: hhvm, tags: [hhvm] }
    - { role: nginx, tags: [nginx] }
    - { role: composer, tags: [composer] }
    - { role: wp-cli, tags: [wp-cli] }
    - { role: wordpress-setup, tags: [wordpress, wordpress-setup] }
