---
- name: restart hhvm
  service: name=hhvm state=restarted

- name: reload php-fpm
  service: name=php5-fpm state=reloaded

- name: reload nginx
  service: name=nginx state=reloaded

- name: reboot
  command: /sbin/reboot
