# ==============================================================================
# Global
# ==============================================================================

www_root: /srv/www
apt_cache_valid_time: 86400

web_sudoers:
  - "/usr/sbin/service hhvm *"
  - "/usr/sbin/service php5-fpm *"

# ==============================================================================
# Common ./roles/common/defaults/main.yml
# ==============================================================================

default_timezone: Etc/UTC

# ==============================================================================
# Ferm ./roles/ferm/defaults/main.yml
# ==============================================================================

ferm_enabled: true

ferm_input_list:
  - type: dport_accept
    dport: [http, https]
    filename: nginx_accept
  - type: dport_accept
    dport: [ssh]
    saddr: ["{{ lookup('pipe', 'curl -4 https://diagnostic.opendns.com/myip') }}"]
  - type: dport_limit
    dport: [ssh]
    seconds: 300
    hits: 20
