# ==============================================================================
# Hosted Sites
# ==============================================================================

hosted_sites:
  apollo.dev:
    site_hosts:
      - apollo.dev
    local_path: ~/dev/apollo.web
    cache:
      enabled: false
      duration: 30s
