# ==============================================================================
# Users
# ==============================================================================

web_user: web
web_group: www-data

users:
  - name: "{{ web_user }}"
    groups:
      - "{{ web_group }}"
  - name: dolson
    groups:
      - "{{ web_group }}"
      - sudo
  - name: sbaer
    groups:
      - "{{ web_group }}"
      - sudo
