# ==============================================================================
# Users
# ==============================================================================

web_user: web
web_group: www-data

users:
  - name: "{{ web_user }}"
    groups:
      - "{{ web_group }}"
