# ==============================================================================
# Global
# ==============================================================================

apt_cache_valid_time: 86400
default_timezone: Etc/UTC
www_root: /srv/www
disable_nginx_default: true

# ==============================================================================
# Ferm
# ==============================================================================

ferm_input_list:
  - type: dport_accept
    dport: [http, https]
    filename: nginx_accept
  - type: dport_accept
    dport: [ssh]
    saddr: ["{{ lookup('pipe', 'curl -4 https://diagnostic.opendns.com/myip') }}"]
  - type: dport_limit
    dport: [ssh]
    seconds: 300
    hits: 20

# ==============================================================================
# SSH
# ==============================================================================

sshd_permit_root_login: true
sshd_password_authentication: true

# ==============================================================================
# Users & SSH
# ==============================================================================

web_user: web
web_group: www-data

users:
  - name: "{{ web_user }}"
    groups:
      - "{{ web_group }}"

web_sudoers:
  - "/usr/sbin/service hhvm *"
  - "/usr/sbin/service php5-fpm *"

# ==============================================================================
# Sites
# ==============================================================================

wordpress_sites:
  example.com:
    site_hosts:
      - example.com
    cache:
      enabled: true
      duration: 30s
