---
ferm_enabled: true
ferm_limit_portscans: false

ferm_default_policy_input: DROP
ferm_default_policy_output: ACCEPT
ferm_default_policy_forward: DROP

ferm_input_group_list: []
ferm_input_host_list: []

ferm_input_list:
  - type: dport_accept
    dport: [http, https]
    filename: nginx_accept
  - type: dport_accept
    dport: [ssh]
    saddr: ["{{ lookup('pipe', 'curl -4 https://diagnostic.opendns.com/myip') }}"]
  - type: dport_limit
    dport: [ssh]
    seconds: 300
    hits: 20
