---
- include: nginx.yml
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ sites_config }}"
    - "group_vars/all/sites.yml"

- name: Inventory folders
  stat:
    path: "{{ www_root }}/{{ item.key }}/web"
  with_dict: hosted_sites
  register: web_root

- name: Create web root
  file:
    path: "{{ www_root }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory
  with_dict: hosted_sites

- name: Create logs folder
  file:
    path: "{{ www_root }}/{{ item.key }}/logs"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory
  with_dict: hosted_sites

- name: Create web folder
  file:
    path: "{{ www_root }}/{{ item.key }}/web"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory
  with_dict: hosted_sites
  when: web_root.stat.isdir is defined and web_root.stat.isdir

- name: Set ACLs
  acl:
    name: "{{ www_root }}"
    recursive: yes
    default: yes
    entity: "{{ web_group }}"
    etype: group
    permissions: rwx
    state: present
  when: sym.stat.islnk is defined and sym.stat.islnk == False
