---
- include: nginx.yml
- include_vars: https://gist.githubusercontent.com/emaildano/c1cd50e966f9c9acabc8/raw/f70951042f96ada32285d6216611d86baacc9d62/sites.yml

- name: Create web root
  file:
    path: "{{ www_root }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory
  with_dict: hosted_sites

- name: Create logs folder
  file:
    path: "{{ www_root }}/{{ item.key }}/logs"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory
  with_dict: hosted_sites

- name: Create web folder
  file:
    path: "{{ www_root }}/{{ item.key }}/web"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory
  with_dict: hosted_sites

- name: Set ACLs
  acl: name=/srv/www recursive=yes entity=www-data etype=group permissions=rwx state=present

- name: Set ACL Default
  acl: name=/srv/www recursive=yes default=yes entity=www-data etype=group permissions=rwx state=present
