---
- include: nginx.yml

- name: Create web root
  file:
    path: "{{ www_root }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    recurse: yes
    mode: g+rws
    state: directory
  with_dict: sites

- name: Create logs folder
  file:
    path: "{{ www_root }}/{{ item.key }}/logs"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    recurse: yes
    mode: g+rws
    state: directory
  with_dict: sites

- name: Create web folder
  file:
    path: "{{ www_root }}/{{ item.key }}/web"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    recurse: yes
    mode: g+rws
    state: directory
  with_dict: sites
