---
- name: Launch Instance
  local_action:
    module: ec2
    key_name: "{{ ec2_keyname }}"
    instance_type: t2.nano
    image: "{{ ec2_ami }}"
    wait: yes
    count: 1
    group: "{{ ec2_security_group }}"
    vpc_subnet_id: "{{ ec2_subnet }}"
    region: "{{ ec2_region }}"
    assign_public_ip: yes
    instance_tags:
      Name: Ansible
  register: ec2

- name: Update inventory
  local_action: add_host hostname={{ item.public_ip }} groupname=Ansible
  with_items: ec2.instances

- name: Add tag to instances
  local_action: ec2_tag resource={{ item.id }} region={{ ec2_region }} state=present
  with_items: ec2.instances
  args:
    tags:
      Name: Ansible

- name: Wait for SSH
  local_action: wait_for host={{ item.public_ip }} port=22 state=started
  with_items: ec2.instances
