---
- name: Create security group
  tags:
    - launch
  local_action:
    module: ec2_group
    name: "{{ ec2_security_group_name }}"
    description: Default Web Server
    region: us-east-1
    vpc_id: vpc-666bb003
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0

- name: Launch instance
  tags:
    - launch
  ec2:
    count: 1
    group: "{{ ec2_security_group }}"
    keypair: "{{ ec2_keypair }}"
    image: "{{ ec2_ami }}"
    instance_tags:
      Name: "{{ ec2_tag_name }}"
    instance_type: "{{ ec2_instance_type }}"
    region: "{{ ec2_region }}"
    wait: true
    vpc_subnet_id: "{{ ec2_subnet }}"
    volumes:
      - volume_size: 10
        volume_type: gp2
        delete_on_termination: true
        device_name: /dev/sdb
  register: ec2

- name: Add new instance to host group
  tags:
    - launch
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: "{{ ec2_tag_name }}"
  with_items: ec2.instances

- name: Wait for SSH to come up
  tags:
    - launch
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: ec2.instances

- name: Terminate instances
  tags:
    - terminate
  ec2:
    state: absent
    region: "{{ ec2_region }}"
    instance_ids: "{{ ec2.instance_ids }}"
    instance_tags:
      Name: "{{ ec2_tag_name }}"
  with_items: ec2.instances
