---
- name: Launch ec2 Instance
  hosts: localhost
  become: "{{ ec2_root }}"
  connection: local
  roles:
    - { role: aws, tags: [aws] }

- name: Configure provisioned servers
  hosts: Ansible
  user: ubuntu
  sudo: yes
  roles:
    - { role: common, tags: [common] }
    - { role: ferm, tags: [ferm] }
    - { role: sshd, tags: [sshd] }
    - { role: php, tags: [php] }
    - { role: hhvm, tags: [hhvm] }
    - { role: nginx, tags: [nginx] }
    - { role: memcached, tags: [memcached] }
    - { role: composer, tags: [composer] }
    - { role: wp-cli, tags: [wp-cli] }
