---
- name: Server
  hosts: localhost
  become: yes
  roles:
    - { role: common, tags: [common] }
    - { role: ferm, tags: [ferm] }
    - { role: sshd, tags: [sshd] }
    - { role: php, tags: [php] }
    - { role: hhvm, tags: [hhvm] }
    - { role: nginx, tags: [nginx] }
    - { role: memcached, tags: [memcached] }
    - { role: composer, tags: [composer] }
    - { role: wp-cli, tags: [wp-cli] }
