---
- name: Setup Hosted Sites
  hosts: all:localhost
  become: yes

  vars_files:
    - roles/nginx/defaults/main.yml

  handlers:
    - include: roles/common/handlers/main.yml

  roles:
    - { role: hosted-sites, tags: [hosted-sites] }
